### ISSUE TITLE
Functioning

### ISSUE THREAD

**Issue by nachopatinoc** [pontiggia/prenotami-bot#3]
Hello, how are you? I Would know if code is avaliable for use

**Comment by pontiggia** [comment]
Hey, at the top of the readme says that the code is outdated.
You could try to run it with some general modifications, but I don't recommend that because I made it 2 years ago and prenotami page change.

Thanks for the interest anyways.

**Comment by nachopatinoc** [comment]
Thanks!!

**Comment by nachopatinoc** [comment]
Hello again, I wanted to know if you knew of any place where I could find another code or someone who has done one. Sorry for the inconvenience.
